### PR TITLE
Check if existing comment contains "Squawk Report" header.

### LINKED ISSUE #476: `upload-to-github` incorrectly overwrites comments from other actions
We've set up many of our GHAs to leave linter comments on PRs, all using the default GitHub Actions bot. I've noticed that if our squawk action runs in the same workflow as one of the other commenting linters, it will often overwrite the comment contents of the other action. I believe this is happening because the `comment_on_pr` function is using an overly-broad filter when looking for an existing comment, grabbing the first comment made by the same bot user that is running squawk:
https://github.com/sbdchd/squawk/blob/c8d416325dedcbc4371c046b7fa5d34f43f6ab41/crates/squawk_github/src/lib.rs#L78-L80

I think we can avoid this by having the filter additionally check the bodies of the comments, looking for the `# Squawk Report` header. This is the approach used by other GHAs like [add-pr-comment](https://github.com/mshick/add-pr-comment), which supports setting a "message ID" that's always embedded in the comment text for use when finding existing comments.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #476

When searching for an existing comment to overwrite, check the body of each comment to see if it includes the expected header. This should prevent Squawk from accidentally overwriting comments generated by other GHAs.

### CODE REVIEW

File: crates/squawk_github/src/lib.rs [hunk 1]
```diff
@@ -69,16 +69,18 @@ pub fn comment_on_pr(
...
 
     info!("checking for existing comment");
-    match comments
-        .iter()
-        .find(|x| x.user.r#type == "Bot" && x.user.login == bot_name)
-    {
+    match comments.iter().find(|x| {
+        x.user.r#type == "Bot"
+            && x.user.login == bot_name
+            && x.body.contains(existing_comment_text_includes)
```
Comment (danxmoran) [inline crates/squawk_github/src/lib.rs:82]: I thought about using `starts_with` here to be even more specific, but I wasn't sure how that would play with the markdown generation

Comment (sbdchd) [reply crates/squawk_github/src/lib.rs:82]: ah is the issue that there's one bot account setup and multiple apps, other than squawk, use it?

Comment (sbdchd) [reply crates/squawk_github/src/lib.rs:82]: can we add a comment explaining the reasoning? otherwise looks good!

**Review by sbdchd — CHANGES_REQUESTED** [review]
Looks good, one minor comment about adding a comment!

File: crates/squawk_github/src/lib.rs (hunk 1 above)
Comment (danxmoran) [reply crates/squawk_github/src/lib.rs:88]: Added!

**Review by sbdchd — APPROVED** [review]
Thank you!!
