### PR TITLE
fix parsing `create view` with nested parens

### LINKED ISSUE #467: Nested query crashes
Possibly related to #463, bumped to 2.2.0 but still getting the following error.

```sql
create table bar ( y int );
create view foo as
  select b.y
  from (( select y from bar )) as b order by y desc;
```

results in 

```
panicked at crates/squawk_parser/src/grammar.rs:2351:5:
assertion failed: p.at_ts(SELECT_FIRST)
   0: squawk::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: squawk_parser::grammar::select_stmt
   8: squawk_parser::grammar::data_source
   9: squawk_parser::grammar::opt_from_clause
  10: squawk_parser::grammar::select_stmt
  11: squawk_parser::grammar::stmt
  12: squawk_parser::grammar::create_view_stmt
  13: squawk_parser::grammar::stmt
  14: squawk_parser::grammar::entry_point
  15: squawk_parser::parse
  16: squawk_syntax::parsing::parse_text
  17: squawk_syntax::<impl squawk_syntax::ast::nodes::SourceFile>::parse
  18: squawk::reporter::check_sql
  19: squawk::reporter::check_files
  20: squawk::reporter::check_and_dump_files
  21: squawk::main
  22: std::sys::backtrace::__rust_begin_short_backtrace
  23: std::rt::lang_start::{{closure}}
  24: std::rt::lang_start_internal
  25: main
  26: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  27: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  28: _start

An internal error has occured with Squawk v2.2.0!
```

### PR DESCRIPTION
**Pull request by chdsbd**
fixes #467

### CODE REVIEW

File: crates/squawk_parser/src/grammar.rs [hunk 1]
```diff
@@ -2709,10 +2709,7 @@ fn data_source(p: &mut Parser<'_>) {
     p.eat(LATERAL_KW);
     match p.current() {
         L_PAREN => {
-            p.bump(L_PAREN);
-            // we're at the start of a nested select statement
-            select_stmt(p, None);
-            p.expect(R_PAREN);
+            tuple_expr(p);
```
Comment (sbdchd) [inline crates/squawk_parser/src/grammar.rs:2712]:
```suggestion
            // TODO: this should be `paren_select` instead of a general `tuple_expr`, since only a select statement is allowed inside
            tuple_expr(p);
```
