### PR TITLE
Fix GitHub comment upload failure for large SQL linting reports

### LINKED ISSUE #603: Squawk report fails to upload to GitHub for large SQL linting jobs
## Background

When performing linting on a large SQL migration (14,000 lines split into 14 files), squawk fails to upload the report as a comment on a GitHub issue.

Observed output:
```
06:51:11 [INFO] no config file found
06:51:11 [INFO] pg version: None
06:51:11 [INFO] excluded rules: []
06:51:11 [INFO] excluded paths: []
06:51:11 [INFO] assume in a transaction: false
06:51:11 [INFO] using github actions client
06:51:11 [INFO] checking files
06:51:11 [INFO] reading content from stdin
06:51:11 [INFO] ignoring empty stdin
06:51:11 [INFO] checking file path: V0009__backfill_part1.sql
06:51:11 [INFO] checking file path: V0010__backfill_part2.sql
06:51:11 [INFO] generating github comment body
06:51:12 [INFO] checking for existing comment
06:51:12 [INFO] creating comment
Error: Upload to GitHub failed

Caused by:
    0: Problem calling GitHub API: https://api.github.com/repos/owner/repo-name/issues/48/comments: Client Error: 422 Unprocessable Entity
    1: https://api.github.com/repos/owner/repo-name/issues/48/comments: Client Error: 422 Unprocessable Entity
```

The job lints many files (~14k lines) and attempts to upload the report as a comment via GitHub Actions. The error consistently appears when the lint job is large. This may indicate a GitHub API or content size limitation when posting the report comment.

## Steps to reproduce

1. Lint a large SQL migration split into multiple files (total lines > 1k).
2. Run squawk via GitHub Actions with report upload enabled.
3. Observe failure when uploading comment.

### Expected
Squawk should either succeed in uploading large reports, or clearly handle/report the GitHub API limit (e.g. by splitting, truncating, or warning).

### Actual
Squawk fails with a 422 error and does not upload the report.

## Environment
- squawk container: `ghcr.io/sbdchd/squawk:sha-fecb7c8@sha256:684339263c1089d34302befd79044cd27b07855cdeb775f0871d79d84238e067`
- SQL files: 14 files, ~14,000 lines total
- GitHub Actions

## Additional info
No config file, no pg version specified, excluded rules/paths empty.

### PR DESCRIPTION
**Pull request by ienugr**
## Summary

This PR fixes issue #603 where Squawk fails to upload large linting reports to GitHub with a 422 "Unprocessable Entity" error.

## Problem

When performing linting on large SQL migrations (14,000+ lines across multiple files), Squawk generates GitHub comments that exceed the API's 65,536 character limit, causing upload failures.

### 1. Size Limit Enforcement
- Added `GITHUB_COMMENT_MAX_SIZE` constant (65,000 chars) with safety margin
- Pre-check comment size before API calls to provide better error messages

### 2. Smart Comment Truncation
- Limit SQL preview to 50 lines per file with truncation notice
- Preserve all violation information while reducing content size

### 3. Summary Mode Fallback
- For very large reports, switch to summary mode that omits SQL content
- Display file statistics, line counts, and violation details
- Clear notice about content omission

### 4. Enhanced Error Handling
- New `CommentTooLarge` error variant with descriptive messages
- Better user feedback when size limits are exceeded

## Changes Made

- **`crates/squawk/src/github.rs`**: Main comment generation logic with size checking and fallback modes
- **`crates/squawk_github/src/app.rs`**: Enhanced error handling for comment size limits
- **`crates/squawk_github/src/lib.rs`**: New error variant for size-related failures

#### Normal comment generation (6 violations)

image

Reference: https://github.com/sbdchd/squawk/pull/608#issuecomment-3166740649

#### SQL truncation (33 violations)

image

Reference: https://github.com/sbdchd/squawk/pull/608#issuecomment-3166741256

#### Multiple files handling

image

Reference: https://github.com/sbdchd/squawk/pull/608#issuecomment-3166742666

#### Error handling for oversized content

```
Error: Upload to GitHub failed

Caused by:
    Comment size error: Comment body is too large (1165116 characters). GitHub API limit is 65,536 characters.
```

Large File Tests:
- File: 60,000+ lines
- Violations: 30,003 issues
- Comment size: 1,165,116 characters (18x over limit)
- Error caught: 'Comment body is too large'

Analysis:
- The fix is working for normal use cases
- Error handling prevents GitHub API failures
- Summary mode logic may need adjustment for extreme cases

All existing tests continue to pass.

Fixes #603

### CODE REVIEW

File: crates/squawk/src/github.rs [hunk 1]
```diff
@@ -320,4 +423,100 @@ ALTER TABLE "core_recipe" ADD COLUMN "foo" integer DEFAULT 10;
...
+        }];
+
+        let body = get_comment_body(&violations, "0.2.3");
+
+        // Debug: Print the actual size to see what's happening
+        println!(
+            "Comment body size: {}, limit: {}",
+            body.len(),
+            super::GITHUB_COMMENT_MAX_SIZE
+        );
```
Comment (sbdchd) [inline crates/squawk/src/github.rs:509]:
```suggestion
```

File: crates/squawk/src/github.rs [hunk 2]
```diff
@@ -320,4 +423,100 @@ ALTER TABLE "core_recipe" ADD COLUMN "foo" integer DEFAULT 10;
 
         assert_snapshot!(body);
     }
+
+    #[test]
+    fn test_sql_truncation() {
```
Comment (sbdchd) [inline crates/squawk/src/github.rs:428]:
```suggestion
    fn sql_truncation() {
```

File: crates/squawk/src/github.rs [hunk 3]
```diff
@@ -212,14 +307,21 @@ fn get_sql_file_content(violation: &CheckReport) -> Result<String> {
     };
 
     let violations_emoji = get_violations_emoji(violation_count);
+    let (display_sql, was_truncated) = truncate_sql_if_needed(sql, MAX_SQL_PREVIEW_LINES);
```
Comment (sbdchd) [inline crates/squawk/src/github.rs:310]:
```suggestion
    let (display_sql, was_truncated) = truncate_sql_if_needed(sql);
```

File: crates/squawk/src/github.rs [hunk 4]
```diff
@@ -189,6 +268,22 @@ const fn get_violations_emoji(count: usize) -> &'static str {
     if count > 0 { "🚒" } else { "✅" }
 }
 
+fn truncate_sql_if_needed(sql: &str, max_lines: usize) -> (String, bool) {
+    let lines: Vec<&str> = sql.lines().collect();
+    if lines.len() <= max_lines {
+        (sql.to_string(), false)
```
Comment (sbdchd) [inline crates/squawk/src/github.rs:274]:
```suggestion
fn truncate_sql_if_needed(sql: &str) -> (String, bool) {
    let lines: Vec<&str> = sql.lines().collect();
    if lines.len() <= MAX_SQL_PREVIEW_LINES {
        (sql.to_string(), false)
```

File: crates/squawk/src/github.rs [hunk 5]
```diff
@@ -189,6 +268,22 @@ const fn get_violations_emoji(count: usize) -> &'static str {
...
+    } else {
+        let truncated_lines = lines[..max_lines].join("\n");
```
Comment (sbdchd) [inline crates/squawk/src/github.rs:276]:
```suggestion
        let truncated_lines = lines[..MAX_SQL_PREVIEW_LINES].join("\n");
```

File: crates/squawk/src/github.rs [hunk 6]
```diff
@@ -174,11 +185,79 @@ fn get_comment_body(files: &[CheckReport], version: &str) -> String {
...
+### **{violations_emoji} {violation_count}** violations across **{file_count}** file(s)
+
+> ⚠️ **Large Report**: This report was summarized due to size constraints. SQL content has been omitted but all violations were analyzed.
+
+---
+{file_summaries}
+
+[📚 More info on rules](https://github.com/sbdchd/squawk#rules)
+
+⚡️ Powered by [`Squawk`](https://github.com/sbdchd/squawk) ({version}), a linter for PostgreSQL, focused on migrations
```
Comment (sbdchd) [inline crates/squawk/src/github.rs:255]: can we de-dupe this substrings that are shared?

**Review by sbdchd — CHANGES_REQUESTED** [review]
Thanks for the PR! Left some minor comments!

**Review by sbdchd — APPROVED** [review]
Thanks!
